//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDClient.ReviewService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/ObjectManagerModels")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://schemas.datacontract.org/2004/07/ObjectManagerModels")]
    [System.SerializableAttribute()]
    public partial class Review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CRUDClient.ReviewService.Person AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MovieIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CRUDClient.ReviewService.Person Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MovieId {
            get {
                return this.MovieIdField;
            }
            set {
                if ((this.MovieIdField.Equals(value) != true)) {
                    this.MovieIdField = value;
                    this.RaisePropertyChanged("MovieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReviewService.IReviewService")]
    public interface IReviewService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/GetAllPersons", ReplyAction="http://tempuri.org/IReviewService/GetAllPersonsResponse")]
        CRUDClient.ReviewService.Person[] GetAllPersons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/GetAllPersons", ReplyAction="http://tempuri.org/IReviewService/GetAllPersonsResponse")]
        System.Threading.Tasks.Task<CRUDClient.ReviewService.Person[]> GetAllPersonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/GetPerson", ReplyAction="http://tempuri.org/IReviewService/GetPersonResponse")]
        CRUDClient.ReviewService.Person GetPerson(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/GetPerson", ReplyAction="http://tempuri.org/IReviewService/GetPersonResponse")]
        System.Threading.Tasks.Task<CRUDClient.ReviewService.Person> GetPersonAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/AddPerson", ReplyAction="http://tempuri.org/IReviewService/AddPersonResponse")]
        int AddPerson(CRUDClient.ReviewService.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/AddPerson", ReplyAction="http://tempuri.org/IReviewService/AddPersonResponse")]
        System.Threading.Tasks.Task<int> AddPersonAsync(CRUDClient.ReviewService.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/UpdatePerson", ReplyAction="http://tempuri.org/IReviewService/UpdatePersonResponse")]
        CRUDClient.ReviewService.Person UpdatePerson(CRUDClient.ReviewService.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/UpdatePerson", ReplyAction="http://tempuri.org/IReviewService/UpdatePersonResponse")]
        System.Threading.Tasks.Task<CRUDClient.ReviewService.Person> UpdatePersonAsync(CRUDClient.ReviewService.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/DeletePerson", ReplyAction="http://tempuri.org/IReviewService/DeletePersonResponse")]
        bool DeletePerson(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/DeletePerson", ReplyAction="http://tempuri.org/IReviewService/DeletePersonResponse")]
        System.Threading.Tasks.Task<bool> DeletePersonAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/GetAllReviews", ReplyAction="http://tempuri.org/IReviewService/GetAllReviewsResponse")]
        CRUDClient.ReviewService.Review[] GetAllReviews();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/GetAllReviews", ReplyAction="http://tempuri.org/IReviewService/GetAllReviewsResponse")]
        System.Threading.Tasks.Task<CRUDClient.ReviewService.Review[]> GetAllReviewsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/GetReview", ReplyAction="http://tempuri.org/IReviewService/GetReviewResponse")]
        CRUDClient.ReviewService.Review GetReview(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/GetReview", ReplyAction="http://tempuri.org/IReviewService/GetReviewResponse")]
        System.Threading.Tasks.Task<CRUDClient.ReviewService.Review> GetReviewAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/AddReview", ReplyAction="http://tempuri.org/IReviewService/AddReviewResponse")]
        int AddReview(CRUDClient.ReviewService.Review review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/AddReview", ReplyAction="http://tempuri.org/IReviewService/AddReviewResponse")]
        System.Threading.Tasks.Task<int> AddReviewAsync(CRUDClient.ReviewService.Review review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/UpdateReview", ReplyAction="http://tempuri.org/IReviewService/UpdateReviewResponse")]
        CRUDClient.ReviewService.Review UpdateReview(CRUDClient.ReviewService.Review review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/UpdateReview", ReplyAction="http://tempuri.org/IReviewService/UpdateReviewResponse")]
        System.Threading.Tasks.Task<CRUDClient.ReviewService.Review> UpdateReviewAsync(CRUDClient.ReviewService.Review review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/DeleteReview", ReplyAction="http://tempuri.org/IReviewService/DeleteReviewResponse")]
        bool DeleteReview(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewService/DeleteReview", ReplyAction="http://tempuri.org/IReviewService/DeleteReviewResponse")]
        System.Threading.Tasks.Task<bool> DeleteReviewAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReviewServiceChannel : CRUDClient.ReviewService.IReviewService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReviewServiceClient : System.ServiceModel.ClientBase<CRUDClient.ReviewService.IReviewService>, CRUDClient.ReviewService.IReviewService {
        
        public ReviewServiceClient() {
        }
        
        public ReviewServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReviewServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReviewServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReviewServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CRUDClient.ReviewService.Person[] GetAllPersons() {
            return base.Channel.GetAllPersons();
        }
        
        public System.Threading.Tasks.Task<CRUDClient.ReviewService.Person[]> GetAllPersonsAsync() {
            return base.Channel.GetAllPersonsAsync();
        }
        
        public CRUDClient.ReviewService.Person GetPerson(int id) {
            return base.Channel.GetPerson(id);
        }
        
        public System.Threading.Tasks.Task<CRUDClient.ReviewService.Person> GetPersonAsync(int id) {
            return base.Channel.GetPersonAsync(id);
        }
        
        public int AddPerson(CRUDClient.ReviewService.Person person) {
            return base.Channel.AddPerson(person);
        }
        
        public System.Threading.Tasks.Task<int> AddPersonAsync(CRUDClient.ReviewService.Person person) {
            return base.Channel.AddPersonAsync(person);
        }
        
        public CRUDClient.ReviewService.Person UpdatePerson(CRUDClient.ReviewService.Person person) {
            return base.Channel.UpdatePerson(person);
        }
        
        public System.Threading.Tasks.Task<CRUDClient.ReviewService.Person> UpdatePersonAsync(CRUDClient.ReviewService.Person person) {
            return base.Channel.UpdatePersonAsync(person);
        }
        
        public bool DeletePerson(int id) {
            return base.Channel.DeletePerson(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePersonAsync(int id) {
            return base.Channel.DeletePersonAsync(id);
        }
        
        public CRUDClient.ReviewService.Review[] GetAllReviews() {
            return base.Channel.GetAllReviews();
        }
        
        public System.Threading.Tasks.Task<CRUDClient.ReviewService.Review[]> GetAllReviewsAsync() {
            return base.Channel.GetAllReviewsAsync();
        }
        
        public CRUDClient.ReviewService.Review GetReview(int id) {
            return base.Channel.GetReview(id);
        }
        
        public System.Threading.Tasks.Task<CRUDClient.ReviewService.Review> GetReviewAsync(int id) {
            return base.Channel.GetReviewAsync(id);
        }
        
        public int AddReview(CRUDClient.ReviewService.Review review) {
            return base.Channel.AddReview(review);
        }
        
        public System.Threading.Tasks.Task<int> AddReviewAsync(CRUDClient.ReviewService.Review review) {
            return base.Channel.AddReviewAsync(review);
        }
        
        public CRUDClient.ReviewService.Review UpdateReview(CRUDClient.ReviewService.Review review) {
            return base.Channel.UpdateReview(review);
        }
        
        public System.Threading.Tasks.Task<CRUDClient.ReviewService.Review> UpdateReviewAsync(CRUDClient.ReviewService.Review review) {
            return base.Channel.UpdateReviewAsync(review);
        }
        
        public bool DeleteReview(int id) {
            return base.Channel.DeleteReview(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteReviewAsync(int id) {
            return base.Channel.DeleteReviewAsync(id);
        }
    }
}
